root: true

parser: '@babel/eslint-parser'

extends:
  - pegasus
  - plugin:react/recommended
  - plugin:jest/recommended

plugins:
  - react-hooks

rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/prop-types: 0

overrides:
  - files:
      - '!src/*'
    extends:
      - pegasus/node

settings:
  react:
    version: detect

env:
  browser: true
