root: true

parser: babel-eslint

extends:
  - standard
  - standard-react
  - plugin:jest/recommended
  - pegasus

plugins:
  - react-hooks
  - jest

rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/prop-types: 0

env:
  browser: true
