root: true

parser: '@babel/eslint-parser'

extends:
  - pegasus
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - plugin:prettier/recommended

rules:
  react/prop-types: 0

overrides:
  - files:
      - '!src/*'
    extends:
      - pegasus/node

settings:
  react:
    version: detect

env:
  browser: true
