name: gh-pages

on:
  push:
    branches: master

env:
  NODE_VERSION: 16

jobs:
  test:
    name: Publish to gh-pages
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: node --version
      - run: npm --version

      - name: NPM Install
        run: npm ci

      - name: Publish to gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          npm run publish:docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
